export interface ReportCategory {
  id: string;
  name: string;
  description: string;
}

export interface ReportItem {
  id: string;
  title: string;
  description: string;
  category: string;
  route?: string;
}

export const REPORT_CATEGORIES: ReportCategory[] = [
  { id: 'area', name: 'Area', description: 'รายงานพื้นที่ให้เช่า' },
  { id: 'contract', name: 'Contract', description: 'รายงานสัญญาและลูกค้า' },
  { id: 'service', name: 'Service', description: 'รายงานงานบริการ' },
  { id: 'collection', name: 'Collective', description: 'รายงานเรียกเก็บ/ยอดขาย' },
  { id: 'finance', name: 'Finance', description: 'รายงานการเงิน' },
  { id: 'budget', name: 'Budget', description: 'รายงานงบประมาณ' },
];

export const REPORT_ITEMS: ReportItem[] = [
  {
    id: 'area_lease_inspection',
    title: 'รายงานตรวจสอบพื้นที่ให้เช่า',
    description: 'แสดงพื้นที่ทั้งหมดที่มีให้เช่า',
    category: 'area',
  },
  {
    id: 'area_current_layout',
    title: 'รายงานผังพื้นที่ให้เช่าปัจจุบัน',
    description: 'แสดงพื้นที่ทั้งหมดที่มีให้เช่าพร้อมสาถนะพื้นที่ปัจจุบัน',
    category: 'area',
  },
  {
    id: 'area_closure_notice',
    title: 'รายงานใบแจ้งปิดปรับปรุงพื้นที่',
    description: 'แสดงข้อมูลใบแจ้งปิดปรับปรุงพื้นที่',
    category: 'area',
  },
  {
    id: 'area_measurement_detail',
    title: 'รายงานรายละเอียดการวัดพื้นที่',
    description: 'แสดงข้อมูลวัดพื้นที่จากการทำการบันทึกการวัดพื้นที่จริง',
    category: 'area',
  },
  {
    id: 'contract_customer_by_branch_1',
    title: 'รายงานข้อมูลลูกค้าตามสาขา',
    description: 'แสดงข้อมูลลูกค้าตามสาขาที่สร้างข้อมูล',
    category: 'contract',
  },
  {
    id: 'contract_quotation_detail',
    title: 'รายงานรายละเอียดใบเสนอราคา',
    description: 'แสดงรายละเอียดใบเสนอราคา',
    category: 'contract',
  },
  {
    id: 'contract_quote_no_booking',
    title: 'รายงานใบเสนอราคาที่ยังไม่ได้ทำสัญญาจอง',
    description: 'แสดงข้อมูลใบเสนอราคาที่อนุมัติแล้วแต่ยังไม่โอนไปทำสัญญาจอง',
    category: 'contract',
  },
  {
    id: 'contract_customer_by_branch_2',
    title: 'รายงานข้อมูลลูกค้าตามสาขา',
    description: 'แสดงข้อมูลลูกค้าตามสาขาที่สร้างข้อมูล',
    category: 'contract',
  },
  {
    id: 'contract_booking_detail',
    title: 'รายงานรายละเอียดสัญญาจอง',
    description: 'แสดงรายละเอียดสัญญาจอง',
    category: 'contract',
  },
  {
    id: 'contract_print_booking_rights',
    title: 'พิมพ์หนังสือแสดงสิทธิ์การจอง',
    description: 'พิมพ์เอกสารสัญญาจอง',
    category: 'contract',
  },
  {
    id: 'contract_booking_no_lease',
    title: 'รายงานสัญญาจองที่ยังไม่ได้ทำสัญญาเช่า',
    description: 'แสดงข้อมูลสัญญาจองที่อนุมัติแล้วแต่ยังไม่โอนไปทำสัญญาเช่า',
    category: 'contract',
  },
  {
    id: 'contract_lease_detail',
    title: 'รายงานรายละเอียดสัญญาเช่า',
    description: 'แสดงรายละเอียดสัญญาเช่า',
    category: 'contract',
  },
  {
    id: 'contract_expiry_check',
    title: 'รายงานตรวจสอบอายุสัญญา',
    description: 'แสดงข้อมูลสัญญาที่กำลังจะหมดอายุตามระยะเวลาที่เลือก',
    category: 'contract',
  },
  {
    id: 'contract_print_lease',
    title: 'พิมพ์สัญญาเช่า',
    description: 'พิมพ์เอกสารสัญญาเช่า',
    category: 'contract',
  },
  {
    id: 'contract_print_calculation',
    title: 'พิมพ์ใบคำนวณ',
    description: 'พิมพ์เอกสารใบสรุปสัญญา',
    category: 'contract',
  },
  {
    id: 'contract_print_renewal_note',
    title: 'พิมพ์บันทึกแนบท้ายต่ออายุสัญญาและปรับเพิ่ม-ลดค่าเช่า',
    description: 'พิมพ์เอกสารใบบันทึกแนบท้ายต่ออายุสัญญาและปรับเพิ่ม-ลดค่าเช่า',
    category: 'contract',
  },
  {
    id: 'contract_lease_data',
    title: 'ข้อมูลสัญญาเช่าพื้นที่',
    description: 'แสดงข้อมูลสัญญาเช่าพื้นที่',
    category: 'contract',
  },
  {
    id: 'contract_cancel_data',
    title: 'ข้อมูลยกเลิกสัญญาเช่าพื้นที่',
    description: 'แสดงข้อมูลยกเลิกสัญญาเช่าพื้นที่ที่ยกเลิกไปแล้ว',
    category: 'contract',
  },
  {
    id: 'contract_print_cancel_note',
    title: 'พิมพ์บันทึกข้อตกลงยกเลิกสัญญาเช่า/สัญญาบริการ',
    description: 'พิมพ์เอกสารใบบันทึกข้อตกลงยกเลิกสัญญาเช่า/สัญญาบริการ',
    category: 'contract',
  },
  {
    id: 'contract_promo_summary',
    title: 'รายงานสรุปงานโปรโมชั่น',
    description: 'แสดงข้อมูลงานโปรโมชั่น',
    category: 'contract',
  },
  {
    id: 'contract_promo_notice',
    title: 'พิมพ์ใบแจ้งงานโปรโมชั่น',
    description: 'พิมพ์เอกสารใบแจ้งงานโปรโมชั่น',
    category: 'contract',
  },
  {
    id: 'contract_print_deposit_refund',
    title: 'พิมพ์ใบแจ้งขอคืนเงินค้ำประกันความเสียหาย',
    description: 'พิมพ์เอกสารใบแจ้งขอคืนเงินค้ำประกันความเสียหายของพื้นที่โปรโมชั้น',
    category: 'contract',
  },
  {
    id: 'service_util_summary_by_customer',
    title: 'รายงานสรุปการใช้สาธารณูปโภคของแต่ละลูกค้าตามสาขา',
    description: 'รายงานสรุปการใช้สาธารณูปโภคของแต่ละลูกค้าตามสาขาแยกตามลูกค้าและใบแจ้งหนี้',
    category: 'service',
  },
  {
    id: 'service_util_usage_table',
    title: 'ตารางการใช้ระบบสาธารณูปโภค',
    description: 'ตารางการใช้ระบบสาธารณูปโภคตามประเภทที่เลือก',
    category: 'service',
  },
  {
    id: 'service_meter_monthly',
    title: 'รายงานสรุปการใช้มิเตอร์น้ำไฟแก๊ส ร้านค้าเช่าประจำเดือน',
    description: 'รายงานสรุปการใช้มิเตอร์น้ำไฟแก๊สทั้งหมดแยกตามร้านค้าเช่า',
    category: 'service',
  },
  {
    id: 'collection_compare_sales',
    title: 'รายงานเปรียบเทียบข้อมูลยอดขายของการเงินกับบัญชี',
    description: 'รายงานเปรียบเทียบข้อมูลยอดขายของการเงินกับบัญชีสำหรับการขายแบบ GP',
    category: 'collection',
  },
  {
    id: 'collection_daily_sales',
    title: 'รายงานยอดขายประจำวันของแต่ละลูกค้าตามสาขา',
    description: 'รายงานยอดขายประจำวันสำหรับการขายแบบ GP ของแต่ละลูกค้าตามสาขา',
    category: 'collection',
  },
  {
    id: 'collection_monthly_sales',
    title: 'รายงานสรุปยอดขายประจำเดือนของแต่ละลูกค้าตามสาขา',
    description: 'รายงานสรุปยอดขายประจำเดือนสำหรับการขายแบบ GP ของแต่ละลูกค้าตามสาขา',
    category: 'collection',
  },
  {
    id: 'collection_rent_calc',
    title: 'ใบคำนวณค่าเช่า/ค่าบริการ ตามยอดขาย',
    description: 'พิมพ์ใบคำนวณค่าเช่า/ค่าบริการ ตามยอดขายให้ผูเช่า',
    category: 'collection',
  },
  {
    id: 'collection_food_court_sales',
    title: 'รายงานยอดขาย Food Court',
    description: 'รายงานยอดขาย Food Court ที่ใช้ระบบ POS เชื่อมต่อกับ SPACE',
    category: 'collection',
  },
  {
    id: 'collection_invoice_incomplete',
    title: 'รายงานสรุปสัญญาที่ออกใบแจ้งหนี้ไม่ครบ',
    description: 'แสดงข้อมูลของรหัสรายได้ในต่ละสัญญาที่ออกใบแจ้งหนี้ไปแล้วและยังไม่ได้ออก',
    category: 'collection',
  },
  {
    id: 'collection_print_invoice',
    title: 'พิมพ์/ยืนยันใบแจ้งหนี้',
    description: 'พิมพ์เอกสารใบแจ้งหนี้',
    category: 'collection',
  },
  {
    id: 'collection_revenue_by_business',
    title: 'รายงานสรุปรายได้ตามประเภทธุรกิจและลูกค้า',
    description: 'แสดงข้อมูลสรุปรายได้แยกประเภทธุรกิจและลูกค้า',
    category: 'collection',
  },
  {
    id: 'collection_revenue_by_branch',
    title: 'รายงานสรุปรายได้ตามสาขา',
    description: 'แสดงข้อมูลสรุปรายได้ตามสาขาแยกตามรหัสรายได้',
    category: 'collection',
  },
  {
    id: 'collection_revenue_by_branch_business',
    title: 'รายงานสรุปรายได้ตามสาขาและประเภทธุรกิจ',
    description: 'แสดงข้อมูลสรุปรายได้ตามสาขาและประเภทธุรกิจ',
    category: 'collection',
  },
  {
    id: 'collection_revenue_by_branch_customer',
    title: 'รายงานสรุปรายได้ตามสาขาและลูกค้า',
    description: 'แสดงข้อมูลสรุปรายได้ตามสาขาและลูกค้า',
    category: 'collection',
  },
  {
    id: 'collection_invoice_daily',
    title: 'รายงานสรุปใบแจ้งหนี้ประจำวัน',
    description: 'แสดงข้อมูลใบแจ้งหนี้',
    category: 'collection',
  },
  {
    id: 'collection_invoice_monthly',
    title: 'รายงานสรุปใบแจ้งหนี้ประจำเดือน',
    description: 'แสดงข้อมูลใบแจ้งหนี้โดยไม่แยกรายได้',
    category: 'collection',
  },
  {
    id: 'collection_invoice_audit',
    title: 'รายงานตรวจสอบการสร้างใบแจ้งหนี้',
    description: 'แสดงข้อมูลใบแจ้งหนี้และสถานะของใบแจ้งหนี้ตามวันที่ใบแจ้งหนี้',
    category: 'collection',
  },
  {
    id: 'collection_invoice_error',
    title: 'รายงานข้อผิดพลาดการประมวลผลสร้างใบแจ้งหนี้',
    description: 'แสดงข้อมูลข้อผิดพลาดการประมวลผลสร้างใบแจ้งหนี้',
    category: 'collection',
  },
  {
    id: 'collection_revenue_by_service_code',
    title: 'Detail of Revenue by Service Code',
    description: 'แสดงข้อมูลรายได้ตามรหัสรายได้ที่เลือก',
    category: 'collection',
  },
  {
    id: 'collection_outstanding_detail',
    title: 'รายงานรายละเอียดหนี้คงเหลือ',
    description: 'แสดงข้อมูลรายละเอียดหนี้คงเหลือทั้งแบบมีหนี้ค้างและไม่มีหนี้ค้าง ณ ปัจจุบัน',
    category: 'collection',
  },
  {
    id: 'collection_aging_by_customer',
    title: 'รายงานลูกหนี้คงค้างแยกตามอายุลูกหนี้',
    description: 'แสดงข้อมูลลูกหนี้คงค้างแยกตามอายุลูกหนี้ ณ ปัจจุบัน',
    category: 'collection',
  },
  {
    id: 'collection_revenue_forecast',
    title: 'รายงานคาดการรายได้',
    description: 'แสดงข้อมูลการคาดการรายได้ตามช่วงเวลาที่กำหนดจากข้อมูลสัญญาเช่า',
    category: 'collection',
  },
  {
    id: 'collection_withholding_tax',
    title: 'รายการภาษีหัก ณ ที่จ่าย',
    description: 'แสดงข้อมูลภาษีหัก ณ ที่จ่าย',
    category: 'collection',
  },
  {
    id: 'collection_overdue_debt',
    title: 'รายงานลูกหนี้ค้างชำระ',
    description: 'แสดงข้อมูลลูกหนี้ค้างชำระปัจจุบันและยอดที่ต้องชำระ',
    category: 'collection',
  },
  {
    id: 'collection_outstanding_by_date',
    title: 'รายงานรายละเอียดหนี้คงเหลือตามวัน',
    description: 'แสดงข้อมูลหนี้คงเหลือตามวันที่ต้องการ',
    category: 'collection',
  },
  {
    id: 'collection_rent_roll',
    title: 'รายงาน Rent Roll',
    description: 'รายงาน Rent Roll',
    category: 'collection',
  },
  {
    id: 'collection_profit_center',
    title: 'รายงานสรุปรายได้ตาม Profit Center',
    description: 'แสดงข้อมูลรายได้แยกตาม Profit Center',
    category: 'collection',
  },
  {
    id: 'collection_revenue_by_building',
    title: 'Revenue by Building',
    description: 'แสดงข้อมูลรายได้แยกตามอาคาร',
    category: 'collection',
  },
  {
    id: 'collection_aging_over_120',
    title: 'รายงานลูกหนี้คงค้างแยกตามอายุลูกหนี้',
    description: 'แสดงข้อมูลหนี้คงค้างแยกตามอายุลูกหนี้โดยจะมีระยะเวลาที่มากกว่า 120 วัน',
    category: 'collection',
  },
  {
    id: 'collection_invoice_receipt_credit',
    title: 'รายงานใบแจ้งหนี้ ,ใบเสร็จ และใบลดหนี้',
    description: 'แสดงข้อมูลรายการใบแจ้งหนี้ ,ใบเสร็จ และใบลดหนี้ตามระยะเวลาที้ต้องการ',
    category: 'collection',
  },
  {
    id: 'collection_aging_summary',
    title: 'รายงานยอดรวมลูกหนี้คงค้างแยกตามอายุลูกหนี้',
    description: 'แสดงข้อมูลยอดรวมหนี้คงค้างแยกตามอายุลูกหนี้',
    category: 'collection',
  },
  {
    id: 'collection_monthly_rent_billing',
    title: 'รายงานรายการเรียกเก็บค่าเช่ารายเดือน',
    description: 'แสดงข้อมูลอัตราการเรียกเก็บค่าเช่ารายเดือนตามข้อมูลสัญญา',
    category: 'collection',
  },
  {
    id: 'collection_erp_posting',
    title: 'รายงานข้อมูลการบันทึกบัญชี',
    description: 'แสดงข้อมูลการบันทึกบัญชีไปยังระบบ ERP',
    category: 'collection',
  },
  {
    id: 'collection_outstanding_by_type',
    title: 'รายงานสรุปหนี้คงเหลือตามวันแยกตามประเภทลูกหนี้',
    description: 'แสดงข้อมูลสรุปหนี้คงเหลือตามวันแยกตามประเภทลูกหนี้',
    category: 'collection',
  },
  {
    id: 'collection_print_credit_note',
    title: 'พิมพ์/ยืนยันใบลดหนี้-ใบแจ้งหนี้',
    description: 'พิมพ์เอกสารลดหนี้-ใบแจ้งหนี้',
    category: 'collection',
  },
  {
    id: 'collection_deposit_check',
    title: 'รายงานตรวจสอบเงินประกัน',
    description: 'แสดงข้อมูลสถานะเงินประกันทั้งหมดตามลูกค้า',
    category: 'collection',
  },
  {
    id: 'collection_credit_note_summary',
    title: 'รายงานสรุปใบลดหนี้-ใบแจ้งหนี้',
    description: 'แสดงข้อมูลใบลดหนี้-ใบแจ้งหนี้แยกตามรายการใบแจ้งหนี้',
    category: 'collection',
  },
  {
    id: 'collection_monthly_credit_note_summary',
    title: 'รายงานสรุปใบลดหนี้ประจำเดือน',
    description: 'แสดงข้อมูลใบลดหนี้ประจำเดือนสรุปตามใบแจ้งหนี้',
    category: 'collection',
  },
  {
    id: 'collection_print_payment_notice',
    title: 'พิมพ์ใบแจ้งเตือนให้ชำระหนี้',
    description: 'พิมพ์เอกสารใบแจ้งเตือนให้ชำระหนี้',
    category: 'collection',
  },
  {
    id: 'collection_payment_notice_overdue',
    title: 'รายงานสรุปใบแจ้งเตือนชำระที่ค้างชำระ',
    description: 'แสดงข้อมูลใบแจ้งเตือนชำระที่ค้างชำระรวมถึงเบี้ยปรับ',
    category: 'collection',
  },
  {
    id: 'collection_payment_notice_daily',
    title: 'รายงานสรุปใบแจ้งเตือนชำระประจำวัน',
    description: 'แสดงข้อมูลสรุปใบแจ้งเตือน',
    category: 'collection',
  },
  {
    id: 'collection_payment_notice_monthly',
    title: 'รายงานสรุปใบแจ้งเตือนชำระประจำเดือน',
    description: 'แสดงข้อมูลสรุปใบแจ้งเตือนชำระรายเดือน',
    category: 'collection',
  },
  {
    id: 'collection_bounced_check',
    title: 'รายงานติดตามยอดหนี้เช็คคืน',
    description: 'แสดงข้อมูลรายงานยอดหนี้เช็คคืนจากใบเสร็จรับเงิน',
    category: 'collection',
  },
  {
    id: 'finance_temp_receipt_form',
    title: 'พิมพ์ฟอร์มใบเสร็จรับเงินชั่วคราว',
    description: 'พิมพ์เอกสารใบเสร็จรับเงินชั่วคราว',
    category: 'finance',
  },
  {
    id: 'finance_tax_receipt_form',
    title: 'พิมพ์ฟอร์มใบกำกับภาษี/ใบเสร็จรับเงิน',
    description: 'พิมพ์เอกสารใบกำกับภาษี/ใบเสร็จรับเงิน',
    category: 'finance',
  },
  {
    id: 'finance_receipt_detail_invoice',
    title: 'รายงานรายละเอียดใบเสร็จรับเงิน (อ้างถึงใบแจ้งหนี้)',
    description: 'แสดงข้อมูลใบเสร็จรับเงิน (อ้างถึงใบแจ้งหนี้)',
    category: 'finance',
  },
  {
    id: 'finance_receipt_detail_revenue',
    title: 'รายงานรายละเอียดใบเสร็จรับเงิน (อ้างถึงรายได้)',
    description: 'แสดงข้อมูลใบเสร็จรับเงิน (อ้างถึงรายได้)',
    category: 'finance',
  },
  {
    id: 'finance_receipt_summary',
    title: 'รายงานสรุปใบเสร็จรับเงิน',
    description: 'แสดงข้อมูลสรุปใบเสร็จรับเงินแสดงประเภทการชำระและผุ้รับเงิน',
    category: 'finance',
  },
  {
    id: 'finance_sales_tax',
    title: 'รายงานภาษีขาย',
    description: 'แสดงข้อมูลภาษีขาย',
    category: 'finance',
  },
  {
    id: 'finance_check_detail',
    title: 'รายงานรายละเอียดเช็ค',
    description: 'แสดงข้อมูลรายละเอียดเช็คจากใบเสร็จรับเงิน',
    category: 'finance',
  },
  {
    id: 'finance_bounced_check',
    title: 'รายงานเช็คคืน',
    description: 'แสดงข้อมูลรายงานยอดหนี้เช็คคืนใบจากใบเสร็จรับเงิน',
    category: 'finance',
  },
  {
    id: 'finance_payment_type_daily',
    title: 'รายงานสรุปประเภทการรับชำระประจำวัน',
    description: 'แสดงข้อมูลสรุปประเภทการรับชำระทั้งหมด',
    category: 'finance',
  },
  {
    id: 'finance_temp_receipt_summary',
    title: 'รายงานสรุปใบเสร็จรับเงินชั่วคราว',
    description: 'แสดงข้อมูลใบเสร็จรับเงินชั่วคราว',
    category: 'finance',
  },
  {
    id: 'finance_receipt_vs_ar',
    title: 'รายงานการรับชำระของลูกหนี้',
    description: 'แสดงข้อมูลรับชำระของเงินเทียบกับใบแจ้งหนี้และยอดคงค้าง',
    category: 'finance',
  },
  {
    id: 'finance_erp_posting',
    title: 'รายงานข้อมูลการบันทึกบัญชี',
    description: 'แสดงข้อมูลการบันทึกบัญชีไปยังระบบ ERP',
    category: 'finance',
  },
  {
    id: 'finance_receipt_daily',
    title: 'รายงานสรุปใบเสร็จรับเงินรายวัน',
    description: 'แสดงข้อมูลสรุปยอดใบเสร็จรับเงินรายวัน',
    category: 'finance',
  },
  {
    id: 'finance_on_account',
    title: 'รายงานสรุป On Account และ เศษสตางค์',
    description: 'แสดงข้อมูลเงิน On Account และ เศษสตางค์',
    category: 'finance',
  },
  {
    id: 'finance_receipt_actual',
    title: 'รายงานสรุปใบเสร็จรับเงิน (Actual)',
    description: 'แสดงข้อมูลสรุปใบเสร็จรับเงินแสดงประเภทการชำระและผุ้รับเงิน',
    category: 'finance',
  },
  {
    id: 'finance_cash_deposit',
    title: 'รายงานนำฝากเงินสดและเช็ค',
    description: 'แสดงข้อมูลรายงานการนำฝากเงินสดและเช็ค กรณีบันทึการนำฝากและบันทึกข้อมูลที่ ERP',
    category: 'finance',
  },
  {
    id: 'finance_cash_receipt',
    title: 'รายงานสำคัญรับเงิน',
    description: 'แสดงข้อมูลการลงบัญชีของใบเสร็จรับเงิน',
    category: 'finance',
  },
  {
    id: 'finance_reconcile',
    title: 'รายงานกระทบยอด',
    description: 'แสดงข้อมูลกระทบยอดระหว่างระบบและ ERP',
    category: 'finance',
  },
  {
    id: 'finance_reconcile_alt',
    title: 'รายงาน Reconcil',
    description: 'แสดงข้อมูลกระทบยอดระหว่างระบบและ ERP',
    category: 'finance',
  },
  {
    id: 'finance_credit_note_detail',
    title: 'รายงานรายละเอียดใบลดหนี้-ใบเสร็จรับเงิน',
    description: 'แสดงข้อมูลรายละเอียดใบลดหนี้-ใบเสร็จรับเงิน',
    category: 'finance',
  },
  {
    id: 'finance_receipt_by_service_code',
    title: 'Receipt Detail of Revenue by Service Code',
    description: 'แสดงข้อมูลการรับ้เงินตามรหัสรายได่',
    category: 'finance',
  },
  {
    id: 'finance_print_credit_note',
    title: 'พิมพ์/ยืนยันใบลดหนี้-ใบเสร็จรับเงิน',
    description: 'พิมพ์เอกสารใบลดหนี้-ใบเสร็จรับเงิน',
    category: 'finance',
  },
  {
    id: 'budget_revenue_main',
    title: 'Detail Of Revenue (รายได้หลัก)',
    description: 'แสดงข้อมูลรายได้หลัก',
    category: 'budget',
    route: '/reports/budget/revenue-main',
  },
  {
    id: 'budget_revenue_discount',
    title: 'Detail Of Revenue (ส่วนลด)',
    description: 'แสดงข้อมูลส่วนลด',
    category: 'budget',
    route: '/reports/budget/revenue-discount',
  },
  {
    id: 'budget_revenue_other',
    title: 'Detail Of Revenue (รายได้อื่น)',
    description: 'แสดงข้อมูลรายได้อื่น',
    category: 'budget',
    route: '/reports/budget/revenue-other',
  },
  {
    id: 'budget_salable_area',
    title: 'Salable Area Report',
    description: 'แสดงข้อมูลSalable Area Report',
    category: 'budget',
    route: '/reports/budget/salable-area',
  },
  {
    id: 'budget_vs_actual',
    title: 'รายงานสรุปรายได้เปรียบเทียบงบประมาณ (Actual)',
    description: 'แสดงข้อมูลรายงานสรุปรายได้จากใบแจ้งหนี้เปรียบเทียบงบประมาณ',
    category: 'budget',
    route: '/reports/budget/vs-budget-actual',
  },
  {
    id: 'budget_vs_income',
    title: 'รายงานสรุปรายได้เปรียบเทียบงบประมาณ (Income)',
    description: 'แสดงข้อมูลรายงานสรุปรายได้จากใบ้สร็จรับเงินเปรียบเทียบงบประมาณ',
    category: 'budget',
    route: '/reports/budget/vs-budget-income',
  },
];
